# Localhost

# Docker DNS resolver.
resolver 127.0.0.11 valid=10s;

server {
	listen  80;
	listen  [::]:80;
	server_name *.localhost localhost ;
	root        /var/www/public;
	index       index.html index.htm index.php;

	location ~* \.php$ {
		fastcgi_pass   app:9000;
		include        fastcgi_params;
		fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param  SCRIPT_NAME     $fastcgi_script_name;
		fastcgi_buffer_size 256k;
		fastcgi_buffers 4 512k;
		fastcgi_busy_buffers_size 512k;
		fastcgi_read_timeout 3600s;
	}

	#error_page  404              /404.html;

	# redirect server error pages to the static page /50x.html
	#
	error_page   500 502 503 504  /50x.html;
	location = /50x.html {
			root   /usr/share/nginx/html;
	}

	# Rewrite requests to `/wp-.*` on subdomain installs.
	if (!-e $request_filename) {
		rewrite /wp-admin$ $scheme://$host$request_uri/ permanent;
		rewrite ^(/[^/]+)?(/wp-.*) /wp$2 last;
		rewrite ^(/[^/]+)?(/.*\.php) /wp$2 last;
	}

	# Global restrictions configuration file.
	# Designed to be included in any server {} block.
	location = /favicon.ico {
		log_not_found off;
		access_log off;
	}

	location = /robots.txt {
		allow all;
		log_not_found off;
		access_log off;
	}

	# Deny all attempts to access hidden files such as .htaccess, .htpasswd, .DS_Store (Mac).
	# Keep logging the requests to parse later (or to pass to firewall utilities such as fail2ban)
	location ~ /\. {
		deny all;
	}

  	# WordPress Permalinks
	location / {
		# include the "?$args" part so non-default permalinks doesn't break when using query string
		try_files $uri $uri/ /index.php?$args;
	}

	# This should match upload_max_filesize in php.ini
	client_max_body_size 150m;

}
