# Application WAF Rules

# Documentation: https://docs.vatu.dev/infrastructure-handbook/server-management/runcloud/firewall

# Use this file to manage the WAF rules for this sites.

# Rules for using this file:
# 1. Where possible, use a filter to trigger the rule, instead of just disabling the rule ID.
# 2. Add a human-readable message in the `msg` attribute explaining why the rule has been added.
# 3. Ensure the `id` attribute increments after the last ID in this file. We always start the IDs at 3000000 (3 million) to avoid rule ID collisions with OWASP Core Rule Set (CRS) and other rulesets.
# 4. Usually you'll want to set the `phase` to be `1`, to detect matches early in the page load process.
# 5. When denying a request, always add `redirect:/RUNCLOUD-MODSEC-WAF-BLOCKED` to the rule to redirect the visitor to a firewall message.
# 6. You may note below that WordPress file paths below do not include /wp/ which is usually included in our current setup. This is to allow for instances where we are hosting a vanilla WordPress site, and why the operator is always the looser contains rather than equals.

# Example syntax:
# 
# SecRule REQUEST_URI "@strmatch /wp-admin/site-health.php" \
#   "id:3000000,\
#   phase:1,\
#   t:none,t:urlDecode,t:lowercase,t:normalizePath,\
#   msg:'Vatu WAF: Enable Site Health',\
#   pass,\
#   ctl:ruleRemoveById=959100"
