---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Workflow: Commit
# Version:  2.0.0
# Author:   Michael Bragg <mike@vatu.dev>

name: 'Commit'

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}--${{ github.ref_name || github.head_ref }}
  cancel-in-progress: true

env:
  COMPOSER_ALLOW_SUPERUSER: "1" # https://getcomposer.org/doc/03-cli.md#composer-allow-superuser

jobs:

  php-security:
    name: 'PHP Security Analysis'
    runs-on: 'ubuntu-24.04'

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php-version:
          - '8.3'

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v4.2.2'

      - name: 'Set up PHP environment.'
        uses: 'shivammathur/setup-php@2.34.1'
        with:
          coverage: 'none'
          ini-values: "memory_limit=-1"
          tools: 'composer'
          ini-file: none
          php-version: "${{ matrix.php-version }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      # - name: "Add Composer config."
      #   run: |
      #     composer config http-basic.satispress.vatu.dev ${{ secrets.COMPOSER_VATU_USERNAME }} ${{ secrets.COMPOSER_VATU_KEY }}

      - name: 'Validate Composer file.'
        run: |
          composer validate --ansi

      - name: 'Get Composer Cache Directory.'
        id: 'composer-cache'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: 'Sets up Caching.'
        uses: 'actions/cache@v4.2.3'
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-build-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-build-

      - name: 'Install dependencies.'
        run: |
          composer install --no-interaction --prefer-dist

      - name: 'Logs debug information.'
        run: |
          php --version
          composer --version

      - name: 'Run security test.'
        run: |
          composer test:security

  php-lint:
    name: 'PHP Lint'
    runs-on: 'ubuntu-24.04'

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php-version:
          - '8.3'

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v4.2.2'

      - name: 'Set up PHP environment.'
        uses: 'shivammathur/setup-php@2.34.1'
        with:
          coverage: 'xdebug'
          ini-values: "memory_limit=-1"
          tools: 'composer'
          ini-file: none
          php-version: "${{ matrix.php-version }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      - name: 'Validate Composer file.'
        run: |
          composer validate --ansi

      - name: 'Get Composer Cache Directory.'
        id: 'composer-cache'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: 'Sets up Caching.'
        uses: 'actions/cache@v4.2.3'
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-tools-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-tools-

      - name: 'Install dependencies.'
        run: |
          composer install --working-dir=tools --no-interaction --prefer-dist

      - name: 'Logs debug information.'
        run: |
          php --version
          composer --version
          php ./tools/vendor/bin/parallel-lint --version
          php ./tools/vendor/bin/phpcs --version

      - name: 'Run PHP Lint tests.'
        run: |
          composer test:lint

  php-analysis:
    name: 'PHP Analysis'
    needs:
      - 'php-security'
      - 'php-lint'
    runs-on: 'ubuntu-24.04'

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php-version:
          - '8.3'

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v4.2.2'

      - name: 'Set up PHP environment.'
        uses: 'shivammathur/setup-php@2.34.1'
        with:
          coverage: 'xdebug'
          ini-values: "memory_limit=-1"
          tools: 'composer'
          ini-file: none
          php-version: "${{ matrix.php-version }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      - name: 'Validate Composer file.'
        run: |
          composer validate --working-dir=tools --ansi --strict
          composer validate --ansi --strict

      - name: 'Get Composer Cache Directory.'
        id: 'composer-cache'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: 'Sets up Dev Tool Caching.'
        uses: 'actions/cache@v4.2.3'
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-tools-${{ hashFiles('tools/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-tools-

      - name: 'Sets up Project Caching.'
        uses: 'actions/cache@v4.2.3'
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-tools-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-build-

      - name: "Build site."
        run: |
          composer install --no-interaction --prefer-dist --no-scripts --no-dev

      - name: 'Install dependencies.'
        run: |
          composer install --working-dir=tools --no-interaction --prefer-dist

      - name: 'Logs debug information.'
        run: |
          php --version
          composer --version
          php ./tools/vendor/bin/phpstan --version

      - name: 'Run PHP Analysis tests.'
        run: |
          composer run test:analysis

  php-compatibility:
    name: 'PHP Compatiblity'
    needs:
      - 'php-security'
      - 'php-lint'
    continue-on-error: ${{ matrix.experimental }}
    runs-on: 'ubuntu-24.04'

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.3'
        experimental: [false]
        # include:
        #   - php-version: '8.4'
        #     experimental: true

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v4.2.2'

      - name: 'Set up PHP environment.'
        uses: 'shivammathur/setup-php@2.34.1'
        with:
          coverage: 'none'
          ini-values: "memory_limit=-1"
          tools: 'composer'
          ini-file: none
          php-version: "${{ matrix.php-version }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      - name: 'Logs debug information.'
        run: |
          php --version
          composer --version

      - name: 'Get Composer Cache Directory.'
        id: 'composer-cache'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Sets up Caching."
        uses: "actions/cache@v4.2.3"
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-tools-${{ hashFiles('tools/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-tools-

      - name: "Install dependencies."
        run: |
          composer install --no-interaction --prefer-dist

      - name: 'Run Compatibility tests.'
        run: |
          composer run test:compatibility -- --runtime-set testVersion ${{ matrix.php-version }}

  php-unit:
    name: 'PHP Unit Tests'
    runs-on: 'ubuntu-24.04'
    needs:
      - 'php-analysis'
      - 'php-compatibility'

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php-version:
          - '8.3'

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v4.2.2'

      - name: 'Set up PHP environment.'
        uses: 'shivammathur/setup-php@2.34.1'
        with:
          coverage: 'xdebug'
          ini-values: "memory_limit=-1"
          tools: 'composer'
          ini-file: none
          php-version: "${{ matrix.php-version }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      # - name: "Add Composer config."
      #   run: |
      #     composer config http-basic.satispress.vatu.dev ${{ secrets.COMPOSER_VATU_USERNAME }} ${{ secrets.COMPOSER_VATU_KEY }}

      - name: 'Validate Composer file.'
        run: |
          composer validate --working-dir=tools --ansi --strict
          composer validate --ansi --strict

      - name: 'Get Composer Cache Directory.'
        id: 'composer-cache'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: 'Sets up Dev Tool Caching.'
        uses: 'actions/cache@v4.2.3'
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-tools-${{ hashFiles('tools/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-tools-

      - name: 'Sets up Project Caching.'
        uses: 'actions/cache@v4.2.3'
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-tools-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-build-

      - name: 'Install dependencies.'
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: 'Logs debug information.'
        run: |
          php --version
          composer --version
          php ./tools/vendor/bin/phpunit --version

      - name: 'Run PHP Unit tests.'
        run: |
          composer dump-autoload --dev
          composer run test:unit

  acceptance:
    name: 'Acceptance'
    runs-on: 'ubuntu-24.04'
    needs:
     - 'php-unit'
    steps:

      - name: 'Skip'
        run: |
          echo "Skipped"

  notify-failure:
    name: "Notify on failure."
    if: ${{ failure() }}
    runs-on: 'ubuntu-24.04'
    steps:
      - name: "Failure notification."
        id: 'slack'
        uses: 'slackapi/slack-github-action@v2.1.0'
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_TOKEN }}
          payload: |
            channel: 'updates-failed'
            text: "${{ github.workflow }} workflow failed for ${{ github.event.repository.name }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "${{ github.workflow }} workflow failed for ${{ github.event.repository.name }}.\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View>"
